# docker-compose.yml
version: '3'

services:
  app:
    depends_on:
      - db
      - elasticsearch
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: chat_system
      RAILS_MAX_THREADS: 5
    volumes:
      - ".:/chat_system"
      - "./config/docker/database.yml:/chat-system/config/database.yml"
    tty: true
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_system
    ports:
      - "3307:3306"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    hostname: elasticsearch
    ports:
      - "9200:9200"