default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  reconnect: false
  host: 127.0.0.1
  pool: 50
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>_development
test:
    <<: *default
    database: <%= ENV['DB_DATABASE'] %>_test
production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>